//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Parking_servisEntities : DbContext
    {
        public Parking_servisEntities()
            : base("name=Parking_servisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CENOVNIK> CENOVNIKs { get; set; }
        public virtual DbSet<PARKING> PARKINGs { get; set; }
        public virtual DbSet<VLASNIK> VLASNIKs { get; set; }
    }
}
